version: "3.7"

services:
  caseirinhos_db:
    container_name: caseirinhos_db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=caseirinhos
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
